version: "3.1"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: deviavir/zenbot:unstable
    volumes:
      - ./simulations/:/app/simulations/
      - ./conf.js:/app/conf.js:ro
      - ./extensions/:/app/extensions/
    restart: always
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - ZENBOT_MONGODB_HOST=mongodb
      - ZENBOT_API_PORT=8080
      - ZENBOT_DEFAULT_SELECTOR=hitbtc.ltc-usdt
      - ZENBOT_DEFAULT_STRATEGY=trend_ema
      - ZENBOT_PROFIT_STOP_ENABLE_PCT=10
      - ZENBOT_PROFIT_STOP_PCT=1
      - CUSTOM_PERIOD=1m
      - CUSTOM_EMA_RATE=5
      - CUSTOM_SELL_RATE=-0.006
    stdin_open: true
    command: trade --paper
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./database:/data/db
    command: mongod --bind_ip=0.0.0.0 --logpath=/dev/null
  # Remove below comments to use this container. "adminMongo is a Web based user interface (GUI) to handle all your MongoDB connections/databases needs."
  #
  #adminmongo:
  #  image: mrvautin/adminmongo
  #  links:
  #    - mongodb
  #  tty: true
  #  ports:
  #    - "127.0.0.1:1234:1234"
  #  environment:
  #    - CONN_NAME=zenbot_mongodb
  #    - DB_HOST=mongodb
  #    - DB_PORT=27017
  #    - HOST=0.0.0.0
  #  command: "npm start"
